### ISSUE TITLE
M script-binding manager-update-all doesn't do anything

### ISSUE THREAD

**Issue by WhoMI7** [po5/mpv_manager#2]
Followed all the steps, installed git and added it to PATH, still `M script-binding manager-update-all` does nothing.
Am I missing something?

**Comment by po5** [comment]
Do you have a manager.json next to mpv.conf? (root of config dir)

**Comment by WhoMI7** [comment]
yes 
![image](https://user-images.githubusercontent.com/93109835/208388171-707d1d1e-dcc6-4d4a-8cf6-729d77a5eae3.png)

**Comment by po5** [comment]
Progress should be printed to console, and your scripts should get replaced/new ones downloaded.

If you're using a custom manager.json, make sure it's valid JSON and send it here.

**Comment by WhoMI7** [comment]
Okay so, I deleted everything from my config and just input.conf with manager keybind and the script was left as it is. And _your_ manager.json was working/started downloading scripts, now I did the same with my json but it isn't downloading anything and not even showing an error.

[manager.txt](https://github.com/po5/mpv_manager/files/10258497/manager.txt)

changed the file extension to txt cause Github won't accept json.

**Comment by po5** [comment]
Missing comma after whitelist line. User error.
```json
  {
    "git":"https://github.com/dyphire/mpv-scripts",
    "whitelist":"chapter%-list%.lua$|track%-list%.lua$"
    "dest":"~~/scripts",
    "branch":"main"
  },
```

**Comment by WhoMI7** [comment]
Yeah, and also I should've been using https://github.com/CogentRedTester/mpv_manager/blob/d3b90e7aec81d96362b172ef6644366f7d9d0dac/manager.lua
since my manager.json was mostly copied from here.
My bad

**Comment by WhoMI7** [comment]
Now that I see, issue still persists. It is just displayed that all files are updated, but it doesn't seem to do anything other than that. Just that single line.
![image](https://user-images.githubusercontent.com/93109835/213459941-97195042-811e-4fd2-b430-d524cf0ff29b.png)
logs: https://pastebin.com/CSPyUnkn
my manager.json : https://pastebin.com/RE8kVhd9

I tried dyphire's [latest mpv release](https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2023.01.18).
And their manager was showing something other than just "all files updated". But error/failed nonetheless.
![image](https://user-images.githubusercontent.com/93109835/213460798-9f671ba4-7fa0-4b1e-8e3d-66dcdba3035c.png)
logs: 
[mpv.log](https://github.com/po5/mpv_manager/files/10457355/mpv.log)
Dyphire's manager.json: https://pastebin.com/m90tdZr7


Now I have some questions.
1. How do I make it work? Maybe it requires external dependency?
2. Why does my manager.json shows "all files updated" when it actually doesn't and even doesn't show any error/failed message.

**Comment by po5** [comment]
This isn't valid JSON.  
Run it through any JSON parser.  
Please stop posting until you do this step.

The script works just fine.
