### ISSUE TITLE
[Feature Request] Backup config directory before updating

### ISSUE THREAD

**Issue by WhoMI7** [po5/mpv_manager#4]
Might be useful if things go south while/after updating.
Using 7z already present in mpv directory.

**Comment by po5** [comment]
Have you ever had things "go south"? What happened?  
I don't see how one can horribly mess up in a way that loses their configs or scripts, this is a hard no unless you can come up with anything.

**Comment by WhoMI7** [comment]
> Have you ever had things "go south"? What happened?
> I don't see how one can horribly mess up in a way that loses their configs or scripts, this is a hard no unless you can come up with anything.

Yes actually. 

See: https://github.com/natural-harmonia-gropius/input-event/issues/34
I added that using manager and the issue started.
Wasn't able to figure out the until a few days ago.

Also, when I added `boss-key.lua` https://github.com/detuur/mpv-scripts/issues/9
Sure all of these might be my dumbness or skill gap since I am not an engineer.
But these do pass as "things going south".

Now I am always uneasy about adding a new script.
That is why now I always make a backup of config directory before even changing an alphabet.
Same goes for manually updating any pre-existing script.

**Comment by po5** [comment]
Well, what's the `manager.json` that caused problems?  
There are no mentions of this script in either of those issues.

I still don't see how there's an issue with the script (there isn't).

**Comment by WhoMI7** [comment]
> Well, what's the manager.json that caused problems?

I never said `manager.json` caused any issue.
Updating the scripts caused them to fight with each other then causing the issue (not in `boss-key.lua` case).

>I still don't see how there's an issue with the script (there isn't).

There isn't yes, what I asked for was an extra feature, I didn't report any issue/bug with your script.
Though it's fine, I guess. Manually backing up takes what? like 10 seconds.
I apologize if I sounded rude anywhere.
